import request from 'graphql-request'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';

import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient('https://api-ap-south-1.graphcms.com/v2/cl3l9hjvabcgh01xnfryi20ht/master');

const QUERY = gql`
    {
      posts {
        id
        title
        slug
        datePublished
        content {
          html
        }
        author {
          name
          avatar {
            url
          }
        }
        coverPhoto {
          url
        }
      }
    }
`;

export async function getStaticProps (){
  const {posts} = await graphcms.request(QUERY);
  return {
    props : {
      posts,
    },
    revalidate : 10,
  };
}

export default function Home({posts}) {
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal Blog | Haziq Bangash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
          key={post.id}
          title={post.title}
          author={post.author}
          coverPhoto={post.coverPhoto}
          datePublished={post.datePublished}
          slug={post.slug} /> 
        ))}
      </main>
    </div>
  )
}
